@startuml

class User {
   Integer id_user
   String username
   String first_names
   String last_Names
   String email
   String password
   String recent_sesion
   String state_sesion 
   --
   validate_password()
   encrypted_Password()
}


@enduml
